<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://www.axway.com/mappingServices/project" createdBy="abinca" lastModifiedBy="abinca" checksumTest="true" creationDate="29/09/2016 18:42:07 +0300" engineType="DML" lastModifiedDate="29/09/2016 18:42:22 +0300" engineVersion="2.1">
   <mappingInformations>
      <mappingInformation state="Inactive" path="Mapping Flows/bd.dmlflw"/>
   </mappingInformations>
</project>